# Generated by Django 2.2.3 on 2019-09-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_auto_20190819_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.CharField(default='http://incitrio.com/wp-content/uploads/2015/01/Apple_gray_logo.png', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.CharField(default='https://www.91-img.com/pictures/129875-v4-apple-iphone-xs-max-mobile-phone-large-1.jpg', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
